site_name: OpenShift Demos and Workshops
theme: 
    name: null
    custom_dir: openshift/
    navigation_depth: 2
    include_homepage_in_sidebar: true
    include_search_page: true
plugins:
    - search

nav:
- Home: 'index.md'
- AppDev:
    - 'AI/ML Workflows on OpenShift': 'aiml-workflows.md'
    - 'DevOps with OpenShift': 'devops-with-openshift.md'
    - 'Helm 3 in Action': 'helm3-in-action.md'
    - 'OpenShift Cloud Native Development Workshop': 'cloud-native-development.md'
    - 'OpenShift Pipelines': 'openshift-pipelines.md'
    - 'Red Hat OpenShift Service Mesh in Action Workshop': 'service-mesh.md'
- Install/Multi-Cloud:
    - 'Azure IPI': 'azure-ipi.md'
    - 'Bare Metal UPI': 'bm-upi.md'
    - 'Disconnected Install': 'disconnected-upi.md'
    - 'Google Cloud IPI': 'gcp-ipi.md'
    - 'vSphere UPI': 'vsphere-upi.md'
- Management/Ops:
    - 'Container Native Virtualization': 'cnv.md'
    - 'OpenShift and Container Storage for Admins': 'admin-storage.md'
    - 'OpenShift Metering': 'metering.md'
- GitOps:
    - 'Getting Started with ArgoCD': 'argocd.md'
