site_name: OpenShift Demos and Workshops
theme: readthedocs

nav:
- Home: 'index.md'
- AppDev:
    - 'OpenShift Pipelines': 'openshift-pipelines.md'
    - 'Helm 3 in Action': 'helm3-in-action.md'
    - 'OpenShift Cloud Native Development Workshop': 'cloud-native-development.md'
    - 'Full Serverless Workflow: Eventing, Serving, and Building': 'serverless-workflow.md'
    - 'Red Hat OpenShift Service Mesh in Action Workshop': 'service-mesh.md'
    - 'Application Performance Monitoring in OpenShift': 'app-monitoring.md'
- Install/Multi-Cloud:
    - 'OSP UPI': 'osp-upi.md'
    - 'RHV IPI': 'rhv-ipi.md'
    - 'vSphere UPI': 'vsphere-upi.md'
    - 'Azure IPI': 'azure-ipi.md'
    - 'Google Cloud IPI': 'gcp-ipi.md'
    - 'Bare Metal UPI': 'bm-upi.md'
- Management/Ops:
    - 'OpenShift and Container Storage for Admins': 'admin-storage.md'
    - 'Managing Operators at scale': 'managing-operators-at-scale.md'
    - 'IBM Multi-Cluster Manager': 'ibm-mcm.md'
    - 'Windows Containers': 'windows-containers.md'
    - 'GitOps on OpenShift': 'gitops-on-openshift.md'
    - 'OpenShift Metering': 'metering.md'


