site_name: OpenShift Demos and Workshops
theme: 
    name: null
    custom_dir: openshift/
    navigation_depth: 1
    include_homepage_in_sidebar: true
    include_search_page: true
plugins:
    - search

nav:
- Home: 'index.md'
- AI/ML:
    - 'AI/ML Workflows on OpenShift': 'aiml-workflows.md'
    - 'Data Engineering with Open Data Hub Workshop': 'data-engineering-workshop.md'
- AppDev:
    - 'DevOps with OpenShift': 'devops-with-openshift.md'
    - 'Getting Started with OpenShift for Developers': 'getting-started-for-devs.md'
    - 'Helm 3 in Action': 'helm3-in-action.md'
    - 'odo Developer CLI': 'odo-developer-cli.md'
    - 'OpenShift Cloud Native Development Workshop': 'cloud-native-development.md'
    - 'OpenShift Pipelines': 'openshift-pipelines.md'
    - 'Red Hat OpenShift Service Mesh in Action Workshop': 'service-mesh.md'
- GitOps:
    - 'Getting Started with ArgoCD': 'argocd.md'
    - 'Using Tekton and ArgoCD': 'gitops-with-cicd.md'
- Install/Multi-Cloud:
    - 'Azure IPI': 'azure-ipi.md'
    - 'Bare Metal UPI': 'bm-upi.md'
    - 'Disconnected Install': 'disconnected-upi.md'
    - 'Google Cloud IPI': 'gcp-ipi.md'
    - 'Installing a Windows Node': 'installing-windows-node.md'
    - 'RHV IPI': 'rhv-ipi.md'
    - 'vSphere IPI': 'vsphere-ipi.md'
    - 'vSphere UPI': 'vsphere-upi.md'
- Management/Ops:
    - 'Cluster Application Migration': 'cluster-application-migration.md'
    - 'Kubernetes Operators': 'kubernetes-operators.md'
    - 'OpenShift and Container Storage for Admins': 'admin-storage.md'
    - 'OpenShift Metering': 'metering.md'
    - 'OpenShift Virtualization': 'openshift-virtualization.md'
